#!/usr/bin/env python
# coding: utf-8

import logging
logging.basicConfig(level=logging.INFO)

from wxslack.slackbot_main import slackbot_main
from wxslack.wxbot_slack import wxbot_main
from wxpy.utils import start_new_thread
from wxpy import embed


start_new_thread(slackbot_main)
start_new_thread(wxbot_main)

embed()


