#!/usr/bin/env python
# coding: utf-8

import logging
logging.basicConfig(level=logging.INFO)

from wxbot_slack import wxbot
from wxpy import embed

def wxbot_main():
    wxbot.join()

from slackbot_main import slackbot_main


    slackbot_main()


